{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "import asyncio\n",
    "from multiprocessing import freeze_support\n",
    "from aiomultiprocess import Pool\n",
    "freeze_support()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "aio process 231718 failed\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/core.py\", line 143, in run_async\n",
      "    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/pool.py\", line 84, in run\n",
      "    task: PoolTask = self.tx.get_nowait()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 135, in get_nowait\n",
      "    return self.get(False)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 122, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: Can't get attribute 'task' on <module '__main__' (built-in)>\n",
      "Process SpawnProcess-66:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/core.py\", line 143, in run_async\n",
      "    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/pool.py\", line 84, in run\n",
      "    task: PoolTask = self.tx.get_nowait()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 135, in get_nowait\n",
      "    return self.get(False)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 122, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: Can't get attribute 'task' on <module '__main__' (built-in)>\n",
      "aio process 231722 failed\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/core.py\", line 143, in run_async\n",
      "    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/pool.py\", line 84, in run\n",
      "    task: PoolTask = self.tx.get_nowait()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 135, in get_nowait\n",
      "    return self.get(False)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 122, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: Can't get attribute 'task' on <module '__main__' (built-in)>\n",
      "Process SpawnProcess-67:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/core.py\", line 143, in run_async\n",
      "    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/pool.py\", line 84, in run\n",
      "    task: PoolTask = self.tx.get_nowait()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 135, in get_nowait\n",
      "    return self.get(False)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 122, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: Can't get attribute 'task' on <module '__main__' (built-in)>\n",
      "aio process 231730 failed\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/core.py\", line 143, in run_async\n",
      "    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/pool.py\", line 84, in run\n",
      "    task: PoolTask = self.tx.get_nowait()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 135, in get_nowait\n",
      "    return self.get(False)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 122, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: Can't get attribute 'task' on <module '__main__' (built-in)>\n",
      "Process SpawnProcess-69:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/core.py\", line 143, in run_async\n",
      "    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/pool.py\", line 84, in run\n",
      "    task: PoolTask = self.tx.get_nowait()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 135, in get_nowait\n",
      "    return self.get(False)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 122, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: Can't get attribute 'task' on <module '__main__' (built-in)>\n",
      "aio process 231726 failed\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/core.py\", line 143, in run_async\n",
      "    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/pool.py\", line 84, in run\n",
      "    task: PoolTask = self.tx.get_nowait()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 135, in get_nowait\n",
      "    return self.get(False)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 122, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: Can't get attribute 'task' on <module '__main__' (built-in)>\n",
      "Process SpawnProcess-68:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/usr/lib/python3.11/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/core.py\", line 143, in run_async\n",
      "    result: R = loop.run_until_complete(unit.target(*unit.args, **unit.kwargs))\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n",
      "    return future.result()\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/home/m4rs/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/pool.py\", line 84, in run\n",
      "    task: PoolTask = self.tx.get_nowait()\n",
      "                     ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 135, in get_nowait\n",
      "    return self.get(False)\n",
      "           ^^^^^^^^^^^^^^^\n",
      "  File \"/usr/lib/python3.11/multiprocessing/queues.py\", line 122, in get\n",
      "    return _ForkingPickler.loads(res)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: Can't get attribute 'task' on <module '__main__' (built-in)>\n"
     ]
    },
    {
     "ename": "CancelledError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mCancelledError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[13], line 13\u001b[0m\n\u001b[1;32m      9\u001b[0m     \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mfor\u001b[39;00m result \u001b[38;5;129;01min\u001b[39;00m pool\u001b[38;5;241m.\u001b[39mmap(task, ns):\n\u001b[1;32m     10\u001b[0m       \u001b[38;5;28mprint\u001b[39m(result)\n\u001b[0;32m---> 13\u001b[0m \u001b[38;5;28;01mawait\u001b[39;00m main()\n",
      "Cell \u001b[0;32mIn[13], line 9\u001b[0m, in \u001b[0;36mmain\u001b[0;34m()\u001b[0m\n\u001b[1;32m      7\u001b[0m ns \u001b[38;5;241m=\u001b[39m [\u001b[38;5;28mint\u001b[39m(\u001b[38;5;241m1e6\u001b[39m) \u001b[38;5;28;01mfor\u001b[39;00m _ \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(\u001b[38;5;241m4\u001b[39m)]\n\u001b[1;32m      8\u001b[0m \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mwith\u001b[39;00m Pool() \u001b[38;5;28;01mas\u001b[39;00m pool:\n\u001b[0;32m----> 9\u001b[0m   \u001b[38;5;28;01masync\u001b[39;00m \u001b[38;5;28;01mfor\u001b[39;00m result \u001b[38;5;129;01min\u001b[39;00m pool\u001b[38;5;241m.\u001b[39mmap(task, ns):\n\u001b[1;32m     10\u001b[0m     \u001b[38;5;28mprint\u001b[39m(result)\n",
      "File \u001b[0;32m~/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/pool.py:145\u001b[0m, in \u001b[0;36mPoolResult.results_generator\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    143\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"Return results one-by-one as they are ready\"\"\"\u001b[39;00m\n\u001b[1;32m    144\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m task_id \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mtask_ids:\n\u001b[0;32m--> 145\u001b[0m     \u001b[38;5;28;01myield\u001b[39;00m (\u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mpool\u001b[38;5;241m.\u001b[39mresults([task_id]))[\u001b[38;5;241m0\u001b[39m]\n",
      "File \u001b[0;32m~/mr-github/rnd/data/python-core/.venv/lib/python3.11/site-packages/aiomultiprocess/pool.py:312\u001b[0m, in \u001b[0;36mPool.results\u001b[0;34m(self, tids)\u001b[0m\n\u001b[1;32m    309\u001b[0m             ready[tid] \u001b[38;5;241m=\u001b[39m result\n\u001b[1;32m    310\u001b[0m             pending\u001b[38;5;241m.\u001b[39mremove(tid)\n\u001b[0;32m--> 312\u001b[0m     \u001b[38;5;28;01mawait\u001b[39;00m asyncio\u001b[38;5;241m.\u001b[39msleep(\u001b[38;5;241m0.005\u001b[39m)\n\u001b[1;32m    314\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m [ready[tid] \u001b[38;5;28;01mfor\u001b[39;00m tid \u001b[38;5;129;01min\u001b[39;00m tids]\n",
      "File \u001b[0;32m/usr/lib/python3.11/asyncio/tasks.py:649\u001b[0m, in \u001b[0;36msleep\u001b[0;34m(delay, result)\u001b[0m\n\u001b[1;32m    645\u001b[0m h \u001b[38;5;241m=\u001b[39m loop\u001b[38;5;241m.\u001b[39mcall_later(delay,\n\u001b[1;32m    646\u001b[0m                     futures\u001b[38;5;241m.\u001b[39m_set_result_unless_cancelled,\n\u001b[1;32m    647\u001b[0m                     future, result)\n\u001b[1;32m    648\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 649\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m future\n\u001b[1;32m    650\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    651\u001b[0m     h\u001b[38;5;241m.\u001b[39mcancel()\n",
      "\u001b[0;31mCancelledError\u001b[0m: "
     ]
    }
   ],
   "source": [
    "async def task(n: int):\n",
    "  print('Computing')\n",
    "  await asyncio.sleep(1)\n",
    "  return 1\n",
    "\n",
    "async def main():\n",
    "  ns = [int(1e6) for _ in range(4)]\n",
    "  async with Pool() as pool:\n",
    "    async for result in pool.map(task, ns):\n",
    "      print(result)\n",
    "\n",
    "\n",
    "await main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
